name: flutter_getx_template
description: Flutter with Getx Template.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  archive: ^3.4.9
  fimber: ^0.7.0
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  flutter_alice: ^1.1.1
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.14.2
  flutter_local_notifications: ^18.0.1
  flutter_map: ^7.0.2
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  latlong2: ^0.9.1
  overlay_support: ^2.1.0
#  syncfusion_flutter_charts: ^27.1.52
  timezone: any
  upgrader: ^11.3.1
  url_launcher: ^6.3.1


dependency_overrides:
  flutter_alice:
    git:
      url: https://github.com/kemalmaulana/flutter-alice.git

dev_dependencies:
  dependency_validator: any
  flutter_lints: ^5.0.0
#  flutter_test:
#    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_unpad.png"
  remove_alpha_ios: true

flutter_native_splash:
  web: false
  color: "#FFFFFF"
  image: "assets/images/img_unpad.png"
  color_dark: "#FFFFFF"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/vector/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
